export {HomePage} from './Noticias/home/home';
export {ConoceUnipoliPage} from './CroquisUni/conoceUnipoli/conoceUnipoli';
export {TabsPage} from './tabs/tabs';
export {HomegPage} from './Noticias/homeg/homeg';
export {HorariosPage} from './HorariosCarre/horarios/horarios';
export {InformacionEventosPage} from './Eventos/informacionEventos/informacionEventos';
export {InformacionPage} from './Eventos/informacion/informacion';
export {GruposPage} from './HorariosCarre/grupos/grupos';
export {GruposAPage} from './HorariosCarre/grupos-a/grupos-a';
export {GruposBPage} from './HorariosCarre/grupos-b/grupos-b';
export {GruposCPage} from './HorariosCarre/grupos-c/grupos-c';
export {GruposDPage} from './HorariosCarre/grupos-d/grupos-d';
export {GruposEPage} from './HorariosCarre/grupos-e/grupos-e';
export {CroquisPage} from './CroquisUni/croquis/croquis';
export { HorariosIswPage } from './HorariosCarre/horarios-isw/horarios-isw';
export { HorariosPyMesPage } from './HorariosCarre/horarios-py-mes/horarios-py-mes';
export { HorariosItmPage } from './HorariosCarre/horarios-itm/horarios-itm';
export { HorariosIrtPage } from './HorariosCarre/horarios-irt/horarios-irt';
export { HorariosCivPage } from './HorariosCarre/horarios-civ/horarios-civ';
export { HorariosAmbPage } from './HorariosCarre/horarios-amb/horarios-amb'; 
export { AreasDeportivasYCafeteriasPage } from './CroquisUni/areas-deportivas-y-cafeterias/areas-deportivas-y-cafeterias'
export { CentroInformacionPage } from './CroquisUni/centro-informacion/centro-informacion';   
export { LaboratoriosPage } from './CroquisUni/laboratorios/laboratorios';
export { Ud1Page } from './CroquisUni/ud1/ud1';  
export { Ud2Page } from './CroquisUni/ud2/ud2'; 
export { Ud3Page } from './CroquisUni/ud3/ud3'; 
export { EnlacesPage } from './enlaces/enlaces';
export { SeleccionarCarreraPage } from './LoginRe/seleccionar-carrera/seleccionar-carrera';
export { LoginPage } from './LoginRe/login/login';
export { AlumnoPage } from './LoginRe/alumno/alumno';
export { RegistroPage } from './LoginRe/registro/registro';
export { OlvidarcontraPage } from './LoginRe/olvidarcontra/olvidarcontra';
export {GrupoambPage} from './HorariosCarre/grupoamb/grupoamb';
export {GrupocivPage} from './HorariosCarre/grupociv/grupociv';
export {GrupoirtPage} from './HorariosCarre/grupoirt/grupoirt';
export {GrupoiswPage} from './HorariosCarre/grupoisw/grupoisw';
export {GrupoitmPage} from './HorariosCarre/grupoitm/grupoitm';
export {GrupopymesPage} from './HorariosCarre/grupopymes/grupopymes';