export {HomePage} from './home/home';
export {ConoceUnipoliPage} from './conoceUnipoli/conoceUnipoli';
export {TabsPage} from './tabs/tabs';
export {HomegPage} from './homeg/homeg';
export {HorariosPage} from './horarios/horarios';
export {InformacionEventosPage} from './informacionEventos/informacionEventos';
export {GruposPage} from './grupos/grupos';
export {CroquisPage} from './croquis/croquis';
export { HorariosIswPage } from './horarios-isw/horarios-isw';
export { HorariosPyMesPage } from './horarios-py-mes/horarios-py-mes';
export { HorariosItmPage } from './horarios-itm/horarios-itm';
export { HorariosIrtPage } from './horarios-irt/horarios-irt';
export { HorariosCivPage } from './horarios-civ/horarios-civ';
export { HorariosAmbPage } from './horarios-amb/horarios-amb'; 
export { CafeteriasPage } from './cafeterias/cafeterias';
export { CanchasPage } from './canchas/canchas';
export { CentroInformacionPage } from './centro-informacion/centro-informacion';   
export { LaboratoriosPage } from './laboratorios/laboratorios';
export { Ud1Page } from './ud1/ud1';  
export { Ud2Page } from './ud2/ud2'; 
export { Ud3Page } from './ud3/ud3'; 